import { NextResponse } from "next/server";
import { requireEditor, failure, HttpError } from "@/lib/http";
import { adminClient, serverClient } from "@/lib/supabase/server";
import { nativeGoogleDestination, nativeWorkspaceDestination } from "@/lib/native-workspace";
import { siteURL } from "@/lib/config";
/** Exchange a trusted app bearer session for an isolated web session. No email is sent,
 * no refresh token is shared with JavaScript, and MCP credentials are rejected. */
export async function POST(request: Request) {
  try {
    if (!request.headers.get("authorization")?.startsWith("Bearer "))
      throw new HttpError(401, "Open this page from the signed-in Mac app.");
    const { user } = await requireEditor(request);
    if (!user.email)
      throw new HttpError(400, "Your account needs an email address.");
    const params = new URL(request.url).searchParams;
    const external = params.get("external") === "1";
    const next = nativeGoogleDestination(params.get("next"));
    if (external && !next) throw new HttpError(400, "Choose a Google connection from Connected apps.");
    const path = params.get("page");
    const focus = new URL(request.url).searchParams.get("focus");
    const destination = nativeWorkspaceDestination(focus && path === "/connections" ? `${path}?focus=${encodeURIComponent(focus)}` : path);
    const db = adminClient();
    const { data: rateAllowed, error: rateError } = await db.rpc(
      "hit_booking_rate_limit",
      {
        p_bucket: `native-session:${user.id}`,
        p_limit: 60,
        p_window_seconds: 3600,
      },
    );
    if (rateError) throw rateError;
    if (!rateAllowed)
      throw new HttpError(
        429,
        "Please wait a moment before reopening this workspace.",
      );
    const { data, error } = await db.auth.admin.generateLink({
      type: "magiclink",
      email: user.email,
    });
    if (error || !data.properties?.hashed_token || data.user.id !== user.id)
      throw new HttpError(
        503,
        "The shared workspace could not be opened. Try again.",
      );
    if (external) {
      const handoff = new URL("/api/native/session", siteURL());
      handoff.searchParams.set("token_hash", data.properties.hashed_token);
      handoff.searchParams.set("user", user.id);
      handoff.searchParams.set("next", next!);
      return Response.json({ url: handoff.toString() }, { headers: { "Cache-Control": "no-store", "Referrer-Policy": "no-referrer" } });
    }
    const client = await serverClient();
    const { data: session, error: verifyError } = await client.auth.verifyOtp({
      type: "email",
      token_hash: data.properties.hashed_token,
    });
    if (verifyError || session.user?.id !== user.id) {
      await client.auth.signOut({ scope: "local" });
      throw new HttpError(401, "Sign in again to open this workspace.");
    }
    return NextResponse.redirect(`${siteURL()}${destination}`, {
      status: 303,
      headers: {
        "Cache-Control": "no-store",
        "Referrer-Policy": "no-referrer",
      },
    });
  } catch (e) {
    return failure(e);
  }
}

/** A one-use Supabase email token transfers the Mac session to the system browser.
 * It is generated by the bearer-only editor exchange above; no email is sent. */
export async function GET(request: Request) {
  const params = new URL(request.url).searchParams;
  const next = nativeGoogleDestination(params.get("next"));
  const token = params.get("token_hash"), expected = params.get("user");
  if (!next || !token || !expected) return NextResponse.redirect(new URL("/login?error=Open%20Google%20setup%20from%20Connected%20apps.", siteURL()), { headers: { "Cache-Control": "no-store", "Referrer-Policy": "no-referrer" } });
  const client = await serverClient();
  const { data: existing } = await client.auth.getUser();
  if (existing.user && existing.user.id !== expected) {
    return NextResponse.redirect(new URL("/connections?error=" + encodeURIComponent("This browser is signed in to a different Concourse account. Sign out before reopening Google setup from your Mac."), siteURL()), { headers: { "Cache-Control": "no-store", "Referrer-Policy": "no-referrer" } });
  }
  const { data, error } = await client.auth.verifyOtp({ type: "email", token_hash: token });
  if (error || data.user?.id !== expected) {
    if (data.session) await client.auth.signOut({ scope: "local" });
    return NextResponse.redirect(new URL("/login?error=Connection%20link%20expired.%20Reopen%20Connected%20apps%20on%20your%20Mac.", siteURL()), { headers: { "Cache-Control": "no-store", "Referrer-Policy": "no-referrer" } });
  }
  return NextResponse.redirect(new URL(next, siteURL()), { status: 303, headers: { "Cache-Control": "no-store", "Referrer-Policy": "no-referrer" } });
}
