// Generated by Tools/generate-design-tokens.py. Edit shared/design/tokens.json.
import Foundation
enum WorkspaceTokens {
    static let accentLight: UInt32 = 0x4F46E5
    static let accentDark: UInt32 = 0x8B8BF5
    static let navigationWidth: CGFloat = 224
    static let pageInset: CGFloat = 32
    static let workspaceTitle: CGFloat = 24
    static let controlRadius: CGFloat = 8
    static let navigationRowHeight: CGFloat = 36
    static let navigationFontSize: CGFloat = 13
    static let brandSize: CGFloat = 16
}
