#!/usr/bin/env python3
"""Generate shared workspace tokens; native semantic surfaces remain in DesignSystem.swift."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
t=json.loads((root/'shared/design/tokens.json').read_text())
swift='// Generated by Tools/generate-design-tokens.py. Edit shared/design/tokens.json.\nimport Foundation\nenum WorkspaceTokens {\n'
for key,value in t.items():
 swift+=f'    static let {key}: '+('UInt32 = 0x'+value if isinstance(value,str) else 'CGFloat = '+str(value))+'\n'
swift+='}\n'
(root/'Sources/Murmur/UI/WorkspaceTokens.swift').write_text(swift)
css='/* Generated by Tools/generate-design-tokens.py. */\n:root {\n'
for key,value in t.items():
 import re
 name=re.sub(r'([A-Z])',lambda m:'-'+m[1].lower(),key)
 css+=f'  --workspace-{name}: '+('#'+value if isinstance(value,str) else str(value)+'px')+';\n'
css+='}\n'
(root/'web/src/app/workspace-tokens.css').write_text(css)
